TODO.md, nats-base-client/internal_mod.ts, nats-base-client/mod.ts, nats-base-client/nats.ts, nats-base-client/types.ts, src/connect.ts, tests/autounsub_test.ts, tests/basics_test.ts, tests/disconnect_test.ts, tests/reconnect_test.ts
made `NatsConnection` an interface - implementation is `NatsConnectionImpl` this will allow js/streaming/nkit clients to not care about the underlying implementation and simply use whatever connection they are given to do their thing.
=> added `PublishOptions` and `NatsConnection` interfaces

nats-base-client/buffer.ts, nats-base-client/parser.ts, tests/buffer_test.ts, tests/parser_test.ts
Safari doesn't yet support ES getter/setter, removed uses of getter in nats-base-client
=> [compat] removed es getter from buffer/parser uses

nats-base-client/options.ts, src/deno_transport.ts, tests/auth_test.ts, tests/basics_test.ts, tests/codec_test.ts, tests/tls_test.ts
- added check to verify that tls is available when a tls option is specified.
- added check for "ConnectionRefused", and typed as NatsErrors - different transports will need to do same.
- added check for authentication token
- added check for connection refused error on client code
- added tests for string/json codecs
- added basic TLS tests - other transports will need to expand according to capabilities.
=> added more tests for connection refused, codecs, tls

nats-base-client/protocol.ts, src/deno_transport.ts
fixed an issue where the close option on the protocol was set after resolving a promise, this created a problem on node platform, where a close event is emitted from the socket and triggers a redial before the flag is set.
=> [fix] internal close latch was set after close completed

nats-base-client/queued_iterator.ts
added minor optimizations to combat memory allocations, and to remove possible subscription latency if messages are pushed into the iterator while suspended in the iterator.
=> minor optimizations

nats-base-client/databuffer.ts, nats-base-client/protocol.ts, src/deno_transport.ts, tests/clobber_test.ts
- increased default flush threshold to 32K
- changed to create a buffer before a read, and eliminate copies
- added clobber test to verify client data is not overwritten by reuse
=> changed reads to allocate a new read buffer per read and thus eliminate buffer copies down stream

nats-base-client/error.ts, nats-base-client/queued_iterator.ts, nats-base-client/subscription.ts, nats-base-client/types.ts, tests/iterators_test.ts
[feat] callback-based subscriptions, invoking the iterator throws an error
[fix] subscription exposes `getPending()`
fixes #42
=> api safety for callback based susbscriptions

examples/nats-rep.ts, nats-base-client/msg.ts, nats-base-client/protocol.ts, nats-base-client/types.ts, tests/headers_test.ts, tests/noresponders_test.ts
JetStream requires some of the respond iterations to include a reply subject (+NXT)
=> [feat] respond allows specifying a reply subject

nats-base-client/protocol.ts, nats-base-client/servers.ts, nats-base-client/transport.ts, nats-base-client/types.ts, tests/events_test.ts, tests/servers_test.ts
By default websocket clients will use the `wss://` protocol and connect to a NATS server. In cases where they are connecting to a proxy, it becomes possible to not only provide the `host:port` portion, but the requirement may be a full URL with a path. The proxy may have some semantic associated with the path portion.
A `URLParseFn` type enables a Transport to pre-process all URLs provided during connect - this allows re-targeting default ports to match for example default `ws://` or `wss://` ports, before the underlying hostport parsing activates.
To capture the initial values specified by a client, such as `ws://server:port/path`, the initial hp specification as modified by `URLParseFn` or not is stored in the `src` property. 
Finally, in cases where they are connecting through a proxy, …
=> websocket client urls/updates

nats-base-client/protocol.ts, tests/properties_test.ts
the `Connect` object was extended with all connection options rather than just the ones expected by the server,
=> connect sends extraneous options

nats-base-client/protocol.ts
The receiving of the info was noted when the PONG for the connection was resolved. If the server sent another info within this timeframe, a double connect is sent resulting in the server disconnecting the client.
FIX #73
=> mark info received right when the first info is processed

nats-base-client/headers.ts, nats-base-client/muxsubscription.ts, tests/headers_test.ts
Added internal property `description`.
Changed internal `error` property to be `code`.
Added computed property `hasError` to return true if code is not 2xx.
Added computed property `status` that returns a formatted string with code/status.
FIX #79
=> The status can now have a description.

nats-base-client/nats.ts, nats-base-client/types.ts, src/deno_transport.ts, tests/basics_test.ts
This change makes it easy to `request()` while specifying a reply subject that is in the client's subscribe permission set.
=> [feat] added `reply` option to RequestOptions 

nats-base-client/bench.ts, nats-base-client/databuffer.ts, nats-base-client/denobuffer.ts, nats-base-client/error.ts, nats-base-client/headers.ts, nats-base-client/heartbeats.ts, nats-base-client/muxsubscription.ts, nats-base-client/nats.ts, nats-base-client/nkeys.ts, nats-base-client/parser.ts, nats-base-client/protocol.ts, nats-base-client/queued_iterator.ts, nats-base-client/request.ts, nats-base-client/servers.ts, nats-base-client/subscription.ts, nats-base-client/subscriptions.ts, tests/headers_test.ts
[fix] removed class field initializers and static fields as the current deno bundler doesn't polyfill.
=> deno bundler safari compatibility

nats-base-client/protocol.ts
The timer creation happens outside of the try catches, so if the initial transport connect fails, it is possible for the timer to trigger in an unhandled context.
See https://github.com/nats-io/nats.js/issues/376
=> connection timeout can fire in an 'unhandled' situation

nats-base-client/denobuffer.ts, nats-base-client/headers.ts
Angular can not use the output because of class field initializers.
This, and the corresponding PR in nats.ws are a work around for https://github.com/nats-io/nats.ws/issues/68
=> Remove class field initializers

nats-base-client/error.ts, nats-base-client/protocol.ts, nats-base-client/subscriptions.ts, nats-base-client/types.ts, tests/auth_test.ts
- [NEW] Added support for authentication expired.
- [NEW] Added Events.Error to provide a mechanism to listen for errors
- [CHANGED] 2 auth errors in a row now correctly closes the client
- [FIX] Process error was calling close, but in the context of connecting if the connection wasn't resolved, it would continue to try to connect after the close.
=> process error enhancements and fix

README.md, examples/nats-pub.ts, examples/nats-rep.ts, examples/nats-req.ts, examples/nats-sub.ts, nats-base-client/msg.ts, nats-base-client/muxsubscription.ts, nats-base-client/nats.ts, nats-base-client/options.ts, nats-base-client/protocol.ts, nats-base-client/types.ts, tests/autounsub_test.ts, tests/basics_test.ts, tests/headers_test.ts, tests/noresponders_test.ts
javascript clients were exposing `headers` and `noResponder` optionsto enable/disable these features.
Go client simply keys from server support. Changed to match.
=> removed client options `headers` and `noResponders` - features auto-set if server supports headers.

CODE-OF-CONDUCT.md, GOVERNANCE.md, MAINTAINERS.md, OWNERS.md, README.md, TODO.md, dependencies.md, nats-base-client/internal_mod.ts, nats-base-client/queued_iterator.ts, nats-base-client/subscription.ts, nats-base-client/subscriptions.ts, tests/sub_extensions_test.ts
- [feat] added an internal yield callback on the subscription to enable support of auto-acks on JetStream
- [feat] added an internal cleanup function for when a subscription is called (such as removing a consumer)
- [doc] deno now formats markdown :)
=> Preparing for JetStream

nats-base-client/authenticator.ts, nats-base-client/internal_mod.ts, nats-base-client/options.ts, nats-base-client/servers.ts, nats-base-client/transport.ts, nats-base-client/types.ts, src/connect.ts, tests/helpers/launcher.ts, tests/servers_test.ts
- [change] refactored transport factory to also provide `defaultPort`, `urlParseFn`, and `factory` - `defaultPort` and `urlParseFn` are transport specific (ie websockets)
- [change] made default hostport calculated from the transport information.
- [removed] default hostport constant
- [fix] lint warnings for snake case json fields
FIXES https://github.com/nats-io/nats.ws/issues/80
=> FIX nats-io/nats.ws/issues/80

doc/snippets/headers.ts, nats-base-client/internal_mod.ts, nats-base-client/options.ts, nats-base-client/types.ts, src/deno_transport.ts
- [feat] added `tls.cert`, `tls.key`, `tls.ca` to make it possible to specify certificate as a string on clients that would allow that (node).
- FIX https://github.com/nats-io/nats.js/issues/395
=> [feat] allow non-file tls certificate configuration

nats-base-client/codec.ts
`Codec` was already generic but `JSONCodec` was not which was preventing us from overriding the `unknown` type.
Now, we can do:
```ts
const jc = JSONCodec<MyType>()
const result = jc.decode(data)
// result type is MyType
```
=> Make JSONCodec generic to allow overriding the returned Codec type

nats-base-client/heartbeats.ts, nats-base-client/protocol.ts, nats-base-client/types.ts, tests/auth_test.ts, tests/doublesubs_test.ts, tests/events_test.ts, tests/heartbeats_test.ts, tests/reconnect_test.ts
chore to cleanup event names to be ES5 compliant
=> [change] [breaking] event names now follow ES5 naming

nats-base-client/jsclient.ts, tests/jetstream_test.ts
[fix] subscribe requires `deliverTo` or it is rejected, likewise pull subscribers cannot specify `deliverTo`
[fail] marked test cross-account pull consumer as failing - needs investigation, but the client is sending a request to a subject that the server can respond to
=> Subscribe requires deliverto

nats-base-client/jslister.ts
When needed to retrieve all streams or consumers instead of a paged list, this simple change makes possible to do something like:
```javascript
for await(const info of jsm.streams.list()) {
console.log(info.config.name); // do whatever you want with the info
}
```
It doesn't break the actual API: `jsm.streams.list().next()` still returns a list for the paged result.
=> implements AsyncIterable<T> for Lister<T>

nats-base-client/mod.ts
exports Debug Events enums so developers can use them
=> fix: export Debug Events

.gitignore, nats-base-client/parser.ts, tests/parser_test.ts
[fix] the reply subject buffer was copied from the offset of the reply rather than the subject, providing the client with an incorrect reply subject.
=> fix incorrect copy of reply subject

nats-base-client/jsbaseclient_api.ts, nats-base-client/jsclient.ts, nats-base-client/jsmsg.ts
Replaced all uses of the nullish operator `??` with `||` as downstream react applications created by `react-create-app` will fail.
=> remove use of nullish operator as react-create-app will fail to build

nats-base-client/subscription.ts, nats-base-client/typedsub.ts, tests/autounsub_test.ts, tests/basics_test.ts, tests/helpers/asserts.ts, tests/helpers/mod.ts, tests/jetstream_test.ts, tests/typedsub_test.ts
subscriptions that specified callbacks didn't have timeouts honored.
=> [fix] subscriptions with callbacks now have timeouts honored - FIX #148

nats-base-client/internal_mod.ts, nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/types.ts, tests/consumeropts_test.ts
Added the ability to initialize a builder with the consumer options, this allows the consumer to be further customized.
FIX #153
=> [fix/feat] consumer options builder doesn't provide access to all the options possible

nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/types.ts, tests/jetstream_test.ts
[FIX] js.subscribe followed nats.go, and option for queue was not exposed, it seems this is now supported.
FIX #nats-io/nats.js/issues/432
=> exposed and enabled queue option for consumer opts

examples/jetstream/js_readme_publish_examples.ts, examples/jetstream/js_readme_push_example.ts, examples/jetstream/jsm_readme_jsm_example.ts, jetstream.md, nats-base-client/types.ts
[FIX] jetstream readme examples
[FIX] expose jetstreamManagers deleteMessage 'erase' argument
=> fix jestream readme examples and expose jsm.deleteMessage() `erase` argument

nats-base-client/types.ts
[FEAT] added `max_msgs_per_subject` option to `StreamConfig`, this option specifies on wildcard streams how many messages to keep per subject.
=> added `max_msgs_per_subject` to `StreamConfig`

examples/jetstream/09_flowcontrol.ts, examples/jetstream/10_heartbeats.ts, jetstream.md, nats-base-client/jsconsumeropts.ts, nats-base-client/jsutil.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jsm_test.ts
[FEAT] options `idle_heartbeat` and `flow_control` to `ConsumerConfig`
[FEAT] added `idleHeartbeat(millis)` and `flowControl()` to `ConsumerOptsBuilder`
[FEAT] added `isHeartbeatMsg()` to simplify checking if a raw message sent to a NATS subscription is a JetStream heartbeat message.
[FEAT] added examples for idle_heartbeat and flow_control
[FEAT] exposed `closed` property on subscription objects - this is a promise that is resolved when a subscription is finished.
=> Added ConsumerConfig idle_heartbeat and flow_control options

.github/workflows/test.yml, nats-base-client/jsbaseclient_api.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jstest_util.ts
[FEAT] added `domain` to `JetStreamOptions`, when set a prefix `$JS.${domain}.API` is set.
[FEAT] `domain` is reported by `JetStreamAccountStats`
=> JS add support for `domain`

.github/workflows/test.yml, examples/jetstream/js_readme_publish_examples.ts, examples/jetstream/js_readme_push_example.ts, examples/jetstream/jsm_readme_jsm_example.ts, jetstream.md, nats-base-client/jsclient.ts, nats-base-client/jsstream_api.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jsm_test.ts
[FEAT] [BREAKING] Slight change to JSM streams `getMessage()` the API the second argument changed from a sequence number to be either `{seq: #}` or `last_by_subject: "my.subject"`, this enables the feature for retrieving the last message in a stream with the specified subject.
The JetStream features in the JavaScript clients are pre-release and subject to changes.
=> last_by_subject JSM.streams.getMessage()

nats-base-client/types.ts
https://github.com/nats-io/nats-architecture-and-design/issues/44
=> [feat] expose `PubAck#domain`- where server can distinguish between two same name streams but in different domains.

nats-base-client/ekv.ts, nats-base-client/kv.ts, nats-base-client/queued_iterator.ts, nats-base-client/subscription.ts, nats-base-client/typedsub.ts, nats-base-client/types.ts, tests/ekv_test.ts, tests/iterators_test.ts, tests/jetstream_test.ts, tests/jsmsg_test.ts, tests/kv_test.ts, tests/protocol_test.ts
while writing some tests for KV changes noticed that some unexpected breaks from iterators were leaving behind subscriptions - this PR solves those problems
=> iterator fixes

nats-base-client/util.ts
changed timeout to pre-generate a stack - in the case of a timeout, the stack will have a context to the operation that failed
=> Better trace on timeout

nats-base-client/util.ts, src/deno_transport.ts, tests/protocol_test.ts
[fix] `extractProtocolMessage`, was loosely testing the result from `protoLen`, which returned -1. In such a case, it was possible to attempt processing a frame that wasn't complete. This only happened during connect.
=> FIX partial frames during connect's peek of the info block

.github/workflows/test.yml, nats-base-client/options.ts, nats-base-client/protocol.ts, nats-base-client/servers.ts, nats-base-client/transport.ts, nats-base-client/types.ts, src/connect.ts, src/deno_transport.ts, tests/basics_test.ts, tests/helpers/mod.ts, tests/jetstream_test.ts, tests/servers_test.ts, tests/timeout_test.ts
Added the ability for client transports to enable dns resolution - currently clients simply pass the server hostname or IP to the network connect function. If specifying `resolve: true` as a connection option, the client will resolve the hostname when attempting to connect to it. If randomize was specified (default), entries are randomized. Note some clients such as nats.ws are unable to resolve, as they WebSocket directly handles the resolution for the connection. If the client fails to resolve any entries, it will throw an error, but the client will attempt to connect to other specified servers if possible.
=> [FEAT] dns resolve of server entries

nats-base-client/nats.ts, src/deno_transport.ts, tests/basics_test.ts
[FIX] in some downstream environments the assertion for the subject doesn't seem to auto-reject properly even if there's a handler associated with the promise.
=> request validation doesn't reject properly in downstream

nats-base-client/jsclient.ts, nats-base-client/kv.ts, nats-base-client/queued_iterator.ts, tests/kv_test.ts
[FEAT] added the ability for a QueuedIterator implementor to attach some data
=> [FEAT] allow access to consumer info in watch for internal extenders

tests/tls_test.ts
test relied on demo.nats.io:4222 being non-tls, this changed recently where the server supports tls/non-tls in the same port.
=> [FIX] tls test using demo.nats.io

nats-base-client/error.ts, nats-base-client/jsbaseclient_api.ts, nats-base-client/nats.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jsm_test.ts
The modification enhances NatsError by adding:
`isJetStreamError(): boolean`
`jsError(): ApiError|null`
This enables clients to test if there's more info to the underlying error
FIX #226
=> [FEAT] surface JS errors as per ADR-7

.github/workflows/test.yml, nats-base-client/jsmconsumer_api.ts, nats-base-client/types.ts, tests/jsm_test.ts
added a typed consumer `update` - while JetStream simply does an `add`, the update api, simply retrieves the consumer, and assigns values present in the update (typed to show what properties are editable) - note that this is only intended for updates to durable consumers.
Modifying a consumer is only supported on nats-server 2.6.4+
=> JSM consumer `update`

examples/jetstream/jsm_readme_jsm_example.ts, nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jsm_test.ts
this creates a breaking change - for API symmetry with update consumer, the name of the stream is now a required argument.
=> typed stream `update`

.github/workflows/test.yml, examples/bench.js, nats-base-client/error.ts, nats-base-client/ipparser.ts, nats-base-client/nats.ts, nats-base-client/nuid.ts, nats-base-client/protocol.ts, src/deno_transport.ts, tests/heartbeats_test.ts, tests/helpers/launcher.ts, tests/sub_extensions_test.ts, tests/tls_test.ts
[CHANGE] [DENO] internals for handling signals in the test framework upgraded to changes from Deno.Signal
[CHANGE] [DENO] tls upgrade changed name of CA property - and instead of a file, takes a string
[BREAKING] [DENO] after this change only Deno 1.16.x or better is compatible with the library.
=> Deno 1.16.x

nats-base-client/kv.ts, nats-base-client/types.ts, tests/kv_test.ts
[FEAT] KvEntry now adds `length` to telegraph the length of the payload - if `headers_only` this value is extracted from the header sent by the server, otherwise, it is calculated from the payload.
[FIX] KvOption didn't expose the storage type for the KV - it is now possible to specify `StorageType.File` (the default) or `StorageType.Memory`.
[FEAT] history() and watch() can now specify `headers_only` as an option.
=> small fixes to KV

Makefile, jetstream.md, nats-base-client/jsclient.ts, nats-base-client/nats.ts, nats-base-client/types.ts, tests/jetstream_test.ts
- [FEAT] jestream apis out of preview
- [FIX] jetstream materialized views marked as beta APIs
- [FIX] `deliver_subject` was not part of ConsumerUpdateConfig
- [DOC] added additional hints about `bind` in the jestream doc
=> removed preview notice from JetStream APIs

.github/workflows/test.yml, nats-base-client/encoders.ts, nats-base-client/protocol.ts, tests/auth_test.ts, tests/tls_test.ts
[FIX] fixed an issue where the encoding data was not working correctly as the base library was using a fast encoding/decoding algorithm which doesn't work correctly for higher UTF code-points. The fix simply delegates to standard TextEncoder/TextDecoder.
FIX #237
=> [FIX] replaced fast encode/decode with TextEncoder/Decoder

nats-base-client/jsclient.ts, nats-base-client/kv.ts, tests/auth_test.ts, tests/helpers/launcher.ts, tests/iterators_test.ts, tests/kv_test.ts
[FEAT] Properly support KV across accounts:
a sample server configuration:
```javascript
accounts: {
A: {
jetstream: true,
users: [{ user: "a", password: "a" }],
exports: [
{ service: "$JS.API.>" },
{ service: "$KV.>" },
{ stream: "forb.>" },
],
},
B: {
users: [{ user: "b", password: "b" }],
imports: [
{ service: { subject: "$JS.API.>", account: "A" }, to: "froma.>" },
{ service: { subject: "$KV.>", account: "A" }, to: "froma.$KV.>" },
{ stream: { subject: "forb.>", account: "A" } },
],
},
},
```
In the above:
- A exports:
-  Its JetStream API  - required to use KV
- A service all subjects relating to KV
- A stream
- B imports:
- The JetStream API
- The KV subjects, using a prefix
- The prefixed stream
In ordered to access the KV, the client in `B`:
- Creates a connection setting the …
=> KV prefix handling

nats-base-client/options.ts, tests/properties_test.ts
If an ambiguous configuration was provided (one that specified `port` and `servers`), the `port` option would be selected, discarding the specified `servers`. The documentation for the JavaScript clients specifies that port is only processed if no servers are specified.
FIX #247
=> [FIX] processOptions processed `port` property before `servers`

.github/workflows/test.yml, nats-base-client/jsclient.ts, nats-base-client/jsutil.ts, tests/jetstream_test.ts
[FIX] nats-server 2.7+ handle mixes of `no_wait` and `expires` are slightly different. Since `no_wait` is exposed, the javascript client handles that option by eliminating any specification of `expires`.
[FIX] nats-server 2.7+ returns a 408 when `expires` triggers - previously it was a NoMessages, the 408 is remapped to the no messages which then is handled properly.
[CHANGE] nats-server 2.7+ allows pull consumers to be ephemeral, added a fix for the determination of the consumer `name`, since previously it was the durable, but now it is the consumer name returned by the create consumer.
=> Fixes associated with NATS server 2.7 behavior changes

.github/workflows/test.yml, nats-base-client/jsconsumeropts.ts, nats-base-client/types.ts, tests/jetstream_test.ts
[FEAT] added ephemeral consumer `inactive_threshold`, (`inactiveEphemeralThreshold(millis) option`)
[FEAT] added pull consumer options `max_batch` (`maxPullBatch(n)`), and `max_expires` (`maxPullRequestExpires(millis)`)
=> new pull consumer and ephemeral consumer options

nats-base-client/servers.ts, tests/jsm_test.ts, tests/servers_test.ts
parsing the hostPort will default the port to 4222 if the platform's URL#port doesn't report default ports for a protocol even if specified in the URL (like 80 or 443).
FIX https://github.com/nats-io/nats.js/issues/478
=> hostPort fixes for http/s protocol default parsing

nats-base-client/options.ts, tests/basics_test.ts, tests/properties_test.ts
[FIX] added check that either servers or port was provided - if both options are provided the client will throw an error, as that creates ambiguity on the purpose of `port` - `port` is only allowed if no servers are specified.
FIX https://github.com/nats-io/nats.js/issues/479
=> [FIX] added constraint to reject options when both servers and port are specified.

nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, src/deno_transport.ts, tests/jsm_test.ts
[FIX] StreamUpdateConfig added `subjects`, also unmarked optional `max_msgs_per_subject`, `max_msg_size`, `discard`, and `duplicate_window` - The update api, makes all these fields optional as it is a partial, but when the StreamConfig is returned, these values will be set to their server default values (thus expected to be set).
[FIX] StreamConfig removes `subjects` as it is provided by the extended interface of StreamUpdateConfig
[CHANGE] jsm.streams.update now takes a Partial<StreamUpdateConfig> - this relaxes all fields to be optional
[FIX] jsm.stream.update(name, Partial<StreamUpdateConfig>) will now set the name field - if the update was done without an initial copy of the stream config, this value might not be set by default and result in the server returning an error
=> Fixes to `StreamUpdateConfig`, `StreamConfig` and jsm.streams.update() signature

nats-base-client/parser.ts
In node, the nbc library conditionally patched buf.subarray as buf.slice because in node, subarray performed copies of the data. This change removes this optimization (as node 17.5.0 seems to internally alias it and thus create an allocation loop which exhausts the stack space).
FIX https://github.com/nats-io/nats.js/issues/483
=> [FIX] node v17.5.0 seems to go in a loop, suspect some internal patch of subarray to slice

.github/workflows/test.yml, nats-base-client/kv.ts, nats-base-client/queued_iterator.ts, nats-base-client/types.ts, tests/kv_test.ts
[FEAT] kv watch now takes a callback that will get called once the entries existing in the kv have been received, this allows for the client to get a notification of when the existing values have been loaded (watch will continue to run, notifying of other changes)
[CHANGE] kv will now use DiscardPolicy.New when creating kvs on servers 2.7.2 or better
Fixes https://github.com/nats-io/nats-architecture-and-design/issues/94
=> KV watch notifications and discard policy

nats-base-client/jsclient.ts, nats-base-client/kv.ts, nats-base-client/types.ts, tests/kv_test.ts
This method allows binding to existing KV without creating it.
=> [FEAT] add method to bind to existing KVs

nats-base-client/jsmsg.ts
[FIX] JsMsg.next() converted in place the expires options to nanos in-place creating the posibility of encoding a nano value twice.
=> Fix possible double conversion to nanos

nats-base-client/authenticator.ts, nats-base-client/internal_mod.ts, nats-base-client/mod.ts, tests/auth_test.ts
[FIX] exported the various `Authenticator` return types
[FIX] exported functions `tokenAuthenticator` and `usernamePasswordAuthenticator`
FIX #275
=> export token/usernamePassword authenticators

.github/workflows/test.yml, nats-base-client/error.ts, nats-base-client/jsclient.ts, nats-base-client/jsutil.ts, nats-base-client/msg.ts, nats-base-client/types.ts, tests/jetstream_test.ts
[FIX] the base client request introspected a message and if an status code was set, it turned that into an error. The logic for this was not quite correct one requirement is for the message payload of this type of error be empty and NATS core currently can only expect error of 503 (no responders). Any interpretation of the status code unless a 503, should be delegated - in this case to JetStream which can then make better interpretation of the code (which could simply be a marker for no messages, or a request timeout on requests that have an expiration.
[CHANGE] js.pull(stream,dur) now also adds an optional expires - the expires also overrides the request timeout.
FIX #273
=> Fixes related to JetStream errors being prematurely processed by the core request layer

nats-base-client/protocol.ts
These could bubble up and be trapped by the runtime, resulting in the client crashing.
FIXES #271
=> FIX unhandled promises on transport.send()

nats-base-client/protocol.ts, tests/auth_test.ts
[FIX] while runtime authorization errors are notified, errors related to connection lastError were not properly reported by the closed() promise - this typically resulted in a "Connection Refused" rather than the actual reason.
FIX #268
=> `conn.closed()` resolved error not always the actual reason for the error

nats-base-client/error.ts, nats-base-client/jsmsg.ts, nats-base-client/muxsubscription.ts, nats-base-client/nats.ts, nats-base-client/protocol.ts, nats-base-client/request.ts, nats-base-client/subscription.ts, nats-base-client/subscriptions.ts, nats-base-client/types.ts, tests/auth_test.ts, tests/protocol_test.ts
[FEAT] request api only rejects responses due to timeouts or no responders, but in the case of permissions, the client may not be able to publish to the request subject or subscribe to the mux inbox, this change rejects the request providing a more context relevant error. Previously it was only possible to learn about the error via the async error notification.
FIX #266
=> Expose permission errors at the request api level

nats-base-client/jsclient.ts, nats-base-client/types.ts, tests/jetstream_test.ts
[FEAT] support rejection of push subscriptions if `push_bound` is reported by the server on non `deliver_group` consumers.
https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-15.md#push-consumer-active-information-and-queue-group-binding
FIX #297
=> [FEAT] support `push_bound`

nats-base-client/jsutil.ts, nats-base-client/types.ts, tests/jetstream_test.ts
[FEAT] support ConsumerConfiguration `backoff` - a list of nanos which changes the behaviour of ack_wait to match the list provided in backoff
FIX #299
=> support ConsumerConfiguration `backoff`

nats-base-client/kv.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/kv_test.ts
=> [FEAT] implements the ability in KV to request a specific revision for a key

nats-base-client/nats.ts, tests/basics_test.ts
When sending a request with a custom subject for the reply, `noMux` must
be set to `true`. In this case, however, the eventual headers were not
forwarded to the server when performing the actual request. With this
commit, the headers are included as well in the `noMux` case.
FIX #305
=> [FIX] Include headers when sending a request with `noMux`

nats-base-client/nats.ts, nats-base-client/types.ts, tests/basics_test.ts, tests/jetstream_test.ts, tests/jsm_test.ts
[FEAT] nc#rtt() returns the number of millis for a round trip to the server
[FEAT] jsm#getAccountInfo() now reports tiered usage and limits
[TEST] added a test validating underlying jetstream error codes
=> misc client parity functionality

nats-base-client/internal_mod.ts, nats-base-client/jsmsg.ts, nats-base-client/nats.ts, nats-base-client/request.ts, nats-base-client/types.ts, tests/auth_test.ts, tests/basics_test.ts, tests/protocol_test.ts
[FEAT] [EXPERIMENTAL] nats core requestMany() - allows implementing scatter gather receiving multi-message responses.
=> [FEAT] [EXPERIMENTAL] requestMany()

nats-base-client/protocol.ts, nats-base-client/request.ts, nats-base-client/transport.ts, src/deno_transport.ts
Another unhandled promise on a K8S environment during the connect/ping exchange an EPIPE was getting generated because of aggressive throttling on resource limits (100 millis of a CPU given to the process).
Verified the change with the help of @arjenvdhave who was kind enough to test and reproduce in his environment.
See https://github.com/nats-io/nats.deno/pull/289#issuecomment-1137372830
=> [FIX] change transport.send() to not return a promise

nats-base-client/kv.ts, nats-base-client/types.ts, tests/jsm_test.ts, tests/kv_test.ts
[FIX] [KV] `placementCluster` was not honored.
[FIX] [KV] `KvStatus` didn't report the storage type or the number of replicas, requiring inspecting the stream
[DEPRECATE] [KV] `backingStore` in `KvStatus` is deprecated, use `storage`
[DEPRECATE] [KV] `bucket_location` in `KvStatus` is deprecated, use `placementCluster`
[CHANGE] [JETSTREAM] removed `template_owner` option from `StreamConfig` as this option is not supported
[CHANGE] [JETSTREAM] `placement`, "deny_delete", "deny_purge" options for stream is now updatable (`StreamUpdateConfig`)
=> cleanup StreamConfig/StreamUpdateConfig and KvOptions/KvStatus options

nats-base-client/jsmstream_api.ts, tests/jsm_test.ts
[FIX] jsm.streams.update() to retrieve the existing stream configuration and merging new options with other values to prevent unexpected changes to the stream configuration.
=> [FIX] [JS] change jsm.streams.update() to apply updates to existing config

nats-base-client/jsmstream_api.ts, nats-base-client/jsutil.ts, nats-base-client/kv.ts, nats-base-client/types.ts, tests/kv_test.ts
- [FEAT] implemented getDirectMessage() experimental feature
- [FEAT] [KV] experimental - KvOptions can now specify `allow_direct` which enables the creation of streams on servers that supported that enable the direct api which may provide better performance on gets for KV.
- [FIX] internal checkJsErrorCode() was passing a status instead of a description, creating error descriptions prefixed by the error code
=> [FEAT] [EXPERIMENTAL] direct get of messages for KV

nats-base-client/jsclient.ts, nats-base-client/jsmsg.ts, nats-base-client/jsutil.ts, nats-base-client/protocol.ts, nats-base-client/semver.ts, nats-base-client/types.ts, tests/basics_test.ts, tests/jetream409_test.ts, tests/jetstream_test.ts
The server will limit the number of messages it sends to the `max_bytes` option. Note that if the stream contains a message with a payload larger than `max_bytes`, the consumer will fail. This means that the iterator will end with an error and callbacks will raise this error.
=> [EXPERIMENTAL] [JETSTREAM] pull consumers can now specify `max_bytes` on `PullOptions`

nats-base-client/jsm.ts, nats-base-client/jsmdirect_api.ts, nats-base-client/jsmstream_api.ts, nats-base-client/kv.ts, nats-base-client/types.ts, tests/jsm_test.ts
[REFACTOR] moved direct API to its own JSM api class
=> [FEAT] [EXPERIMENTAL] added support for next_by_subj to direct stream api

nats-base-client/jsclient.ts, tests/jetstream_test.ts
This has the effect of failing `consumerInfo()` on the subscription
FIX #329
=> [FIX] name of the consumer was not captured when binding to an ephemeral

nats-base-client/codec.ts, nats-base-client/jsmdirect_api.ts, nats-base-client/jsutil.ts, nats-base-client/types.ts, nats-base-client/util.ts, tests/jetstream_test.ts
[ADD] added models for configuring StreamConfig.republish
=> [DOC] added JSDoc so that the API for the client can be generated and made available

nats-base-client/jsclient.ts, tests/jetstream_test.ts
[FEAT] added the ability for jetstream publish to specify {retries: number, retry_delay: number} to republish a jetstream message if a 503 is received.
=> JS Republish on 503

nats-base-client/jsmdirect_api.ts, tests/jsm_test.ts
[FEAT] Direct API get for last message by subject will now set the subject as part of the request subject, rather than include it on the payload of the request. This allows for downstream clients, such as KV, to clamp on permissions for a GET.
=> Direct API get last_by_subject enhancement

nats-base-client/kv.ts, nats-base-client/types.ts, tests/kv_test.ts
[FEAT] republish configuration can be applied to kv
[DEPRECATED] KvOptions.maxBucketSize, KvOptions.backingStore, KvOptions.placementCluster, are deprecated, use KvOptions.max_bytes, KvOptions.storage and KvOptions.placement instead. This normalizes some of the configuration properties with the Go client, and their associated StreamConfiguration options.
=> KV republish and configuration option changes

nats-base-client/options.ts, nats-base-client/types.ts, src/deno_transport.ts, tests/tls_test.ts
servers that enable `allow_non_tls` report that they have `tls_available`. This fix enables auto-upgrade by the client to a tls connection unless the `tls` connect option is set to `null`. Previously the client was only responding to `tls_required`.
=> [FIX] support tls_available

nats-base-client/kv.ts, tests/kv_test.ts
=> [FIX] kv status is exposed to the client as millis on set, but on status() it was returned raw in nanos

nats-base-client/error.ts, nats-base-client/idleheartbeat.ts, nats-base-client/jsclient.ts, nats-base-client/jsutil.ts, nats-base-client/queued_iterator.ts, nats-base-client/types.ts, tests/idleheartbeats_test.ts, tests/jetstream_test.ts
[FEAT] added optional heartbeat checks to js#fetch()
[FEAT] added optional heartbeat checks to js#subcribe()
=> consumer heartbeats

nats-base-client/objectstore.ts, tests/objectstore_test.ts
[FIX] fixed an issue where the correct info for an object entry was not calculated when the entry was empty or didn't have pending chunk changes that were unprocessed.
[FIX] made the underlying stream info requests trap the stream not found and instead return "object store not found" [TEST] added more tests to object store
FIX #357
=> [FIX] fixed an issue where the correct info for an object entry was not calculated

nats-base-client/jsmstream_api.ts, nats-base-client/kv.ts, nats-base-client/objectstore.ts, nats-base-client/types.ts, tests/jsm_test.ts, tests/kv_test.ts, tests/objectstore_test.ts
[FEAT] added `jsm.streams.listKvs()` to provide a list of all the `KvStatus` for all streams that use the kv naming strategy.
[FEAT] [BETA] added `jsm.streams.listObjectStores()` to provide a list of all the `ObjectStoreStatus` for all streams that use the objectstore naming strategy.
[FEAT] [KV] `KvStatus` now has the property `streamInfo` with the `StreamInfo` for the KV.
[CHANGE] [BREAKING] [KV] `KvStatus.bucket` is now the user-specified name of the KV used when created - not the stream backing it. This is consistent with the Go client. Previously it returned `KV_` + name. For the actual stream name see `KvStatus.streamInfo.config.name`
[CHANGE] `ObjectStoreInfo` is deprecated use `ObjectStoreStatus` instead.
=> list kvs and objectstores

.github/workflows/test.yml, nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, tests/jsm_test.ts, tests/jstest_util.ts
[FEAT] added internal pagination to `jsm.streams.info()`, if required, the call will collect the necessary pages and merge `subjects`. `StreamInfoRequestOptions` now also has support for `ApiPagedRequest`.
[FIX] `Lister` interface was missing `Symbol.asyncIterator`, so it couldn't be used directly as intended.
=> StreamInfo pagination support

nats-base-client/jsclient.ts, nats-base-client/jsmconsumer_api.ts, nats-base-client/kv.ts, nats-base-client/nats.ts, nats-base-client/protocol.ts, nats-base-client/semver.ts, tests/basics_test.ts, tests/jetstream_test.ts, tests/jsm_test.ts, tests/kv_test.ts, tests/semver_test.ts
[FEAT] added mechanism where a `Feature` can be disabled by the user. This requires casting the connection to a `NatsConnectionImpl`, and then accessing the `Features` controller as `nc.features.disable(Feature)`. This is an experimental feature, currently supporting a very small number of options
=> Feature disablements

nats-base-client/objectstore.ts, tests/objectstore_test.ts
Link configurations must be routed through the `link()` API. This matches changes made to the go client in https://github.com/nats-io/nats.go/pull/1057/files
=> [FIX] [OS] made `put()` reject link configurations

nats-base-client/jslister.ts, nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, tests/jsm_test.ts
This will limit the list to include streams that include the specified subject.
=> [FEAT] `jsm.streams.list()` can now specify a subject filter

nats-base-client/base64.ts, nats-base-client/objectstore.ts, tests/objectstore_test.ts
I'm opening this PR mainly to open a discussion around language cross compatibility (with Go). This would be a breaking change.
https://github.com/nats-io/nats.go/blob/f4102422df7df83b2032318fd14a248c45f113e1/object.go#L442
also related: https://github.com/nats-io/nats.py/pull/331#pullrequestreview-1116024414
=> [FIX] cross language compatible meta subject

nats-base-client/kv.ts, nats-base-client/types.ts, tests/jsm_test.ts
https://github.com/nats-io/nats-architecture-and-design/issues/160
=> [FEAT] [JS] discard_new_per_subject functionality

nats-base-client/jsclient.ts, tests/jetstream_test.ts, tests/jsm_test.ts
- [CHANGE] [JS] ordered consumers now default to memory storage and no replicas
- [CHANGE] [JS] ordered consumers now recreate the consumer if heartbeats are missed. Note that the client will not get a notification since the client will try to recover. This is also a change for iterators since the ordered consumer iterator will now resume when the consumer
is recreated. For non-ordered consumers, any error will be notified on the callback until the subcription ends. Iterator based consumers will stop with the missed heartbeat error.
- [FIX] [JS] publishing retries now properly handle timeouts
FIX #375
=> Ordered consumer changes

nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, tests/jsm_test.ts
An optional subject can be specified to filter to include only streams that contain or match the specified subject (can contain wildcards).
=> [FEAT] [JS] added JSM API to list stream names

nats-base-client/queued_iterator.ts, nats-base-client/subscription.ts, tests/basics_test.ts, tests/drain_test.ts
[FIX] fixed an issue where if an unsubscribe was set on a subscription and the subscription used an iterator, the iterator was stopped immediately rather than waiting for the currently in-flight messages to be processed.
=> subscription closed, terminated iterators that had pending messages

README.md, nats-base-client/protocol.ts, src/deno_transport.ts, tests/basics_test.ts, tests/drain_test.ts, tests/headers_test.ts, tests/jsmuxedinbox_test.ts
[FIX] added a catch to the initial pong promise as it seems possible in some difficult scenarios in node for the pong to be rejected before other handlers are setup. See https://github.com/nats-io/nats.js/issues/523
[LINT] fixed some linter and fmt warnings
=> Early PONG rejection

nats-base-client/subscriptions.ts, tests/auth_test.ts
This is actually an edge case trying a sub that didn't have permissions (on the same subject) due to buffering etc, and because the server doesn't provide the ID the subscription ID that created the problem, writing the test with the same subscription would end up calling the handler for the first subscription twice, and that made a negative test fail.
Now the part that I am not sure about is that if there's a disconnect and in the meanwhile, the permission has changed, the reconnect won't re-establish the sub. Possibly this means dispatching of the error should internally mark that object as reaped while keeping the sub registration open (so reconnect can resub).
This is why this sort of behavior where sub permission errors are not final is kind of a tricky condition. While in some cases …
=> sub discard

nats-base-client/authenticator.ts, tests/auth_test.ts, tests/authenticator_test.ts, tests/helpers/launcher.ts
[FEAT] authenticator functions now delay executing user functions until required. This means that user functions can provide different authentication values when the authentication happens. Because these functions execute during the client handshake, they must not take significant time or the server may timeout the authentication process. The recommended strategy is for the client to asynchronously maintain up-to-date credentials, that can be presented when required.
[FEAT] All authenticators can now provide functions for all their arguments.
=> Authenticator Enhancements

nats-base-client/protocol.ts, tests/auth_test.ts
if during processInfo there was some sort of exception (most likely it is a bad authenticator), the error was transformed to a BadAuthentication, this was incorrect and instead what should happen is the error is telegraphed as it is to the client.
=> [FIX] processInfo random error was mapped as BadAuthentication, when it should just be whatever error it was

nats-base-client/protocol.ts, nats-base-client/servers.ts, src/deno_transport.ts, tests/reconnect_test.ts
[FIX] if the client attempted to close() while in a disconnected state, the close promise wouldn't resolve because under the covers if the policy allowed the client to reconnect, it would still be trying to do so.
=> [FIX] properly close() when in a disconnected state

nats-base-client/jsclient.ts, nats-base-client/subscription.ts, tests/jetstream_test.ts
[FIX] Fixes an issue where a drain() call was not catching a possible promise rejection of a PONG, this happened for inflight requests while disconnected from the nats-server.
FIX #416
=> [FIX] jetstream `fetch()` error while disconnected from the server

nats-base-client/queued_iterator.ts, tests/jetstream_test.ts
[FIX] if internal code inserted an error into an iterator by pushing a function that set the error condition, the iterator wouldn't immediately yield the error, as the error check happened prior to the execution of the function
[TEST] added tests for idle heartbeat conditions.
=> [internal] pushing a funtion to a queued iterator that sets an error is ignored until the next yield

nats-base-client/protocol.ts, tests/basics_test.ts, tests/reconnect_test.ts
[FIX] protocol errors (any unknown error from the server) was handled by the client with a `close()`. Now while the connection could reset, reconnects are honored.
FIX #421
=> [FIX] protocol errors shoudn't close() the client

nats-base-client/internal_mod.ts, nats-base-client/jsutil.ts, nats-base-client/mod.ts, nats-base-client/service.ts, tests/service_test.ts
- [CHANGE] separated service error header into two headers, one with the code the other with the message
- [CHANGE] clamped down on the service name to be a filesystem safe name 
- [CHANGE] STATUS is now STATS to better reflect its intention, things named with status, changed to be stats. 
- [CHANGE] PING now returns the name and id of the service and is intended for client RTT calculations - [CHANGE] control subject (for invoking monitoring) can now specify a prefix (this replaces `$SRV` and is intended for cross account).
=> [CHANGE] SERVICE API changes

nats-base-client/nats.ts, nats-base-client/types.ts, tests/basics_test.ts, tests/mrequest_test.ts
[CHANGE] mrequest iterator signature - possible errors at core NATS level can only be sub/no responder type errors which should fail the request
=> [CHANGE] [experimental] mrequest iterator signature

nats-base-client/service.ts, tests/drain_test.ts, tests/helpers/service_metadata.ts, tests/service_test.ts
cross client service metadata verification
requires a service:
- that echos back payload
- returns a service error message if payload is empty
- throws an error (or registers an internal error) if the payload value is "error"
clients can execute as:
`deno run -A https://raw.githubusercontent.com/nats-io/nats.deno/main/tests/helpers/service_metadata.ts --server demo.nats.io --name serviceName`
=> cross-client service verification tool

nats-base-client/nkeys.ts, src/deno_transport.ts
[BUMP] nkeys.js dependency to 1.0.4 as downstream projects (nats.ws) when in a cjs module configuration with some bundlers would failed to propagate the dependency
[BUMP] client version to 1.10.2
=> [BUMP] nkeys.js dependency to 1.0.4

nats-base-client/protocol.ts, tests/auth_test.ts
This type of recovery can only happen if the client implements a jwt/creds handler
=> [FIX] prevent client from closing due to expired credentials if there's a subsequent reconnect after an expired credential

nats-base-client/internal_mod.ts, nats-base-client/mod.ts, nats-base-client/objectstore.ts, nats-base-client/types.ts, tests/service_test.ts
FIX https://github.com/nats-io/nats.ws/issues/182
=> [FEAT] [OS] expose timeout on put, for really large assets, it is possible for the publish request to timeout

nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/jsmconsumer_api.ts, nats-base-client/semver.ts, nats-base-client/types.ts, src/deno_transport.ts, tests/jetstream_test.ts, tests/jsm_test.ts
[FEAT] consumer `filter_subjects` support - this feature is exclusive of the `filter_subject` but allows a consumer to filter multiple subjects in a stream. To set, specify `filter_subjects` instead of `filter_subject` or if using consumer options builder `filterSubject()` can be called multiple times.
[CHANGE] `filter_subject` (and `filter_subjects`) can be updated, the server removed this restriction
=> [FEAT] consumer `filter_subjects`

nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/jsmconsumer_api.ts, nats-base-client/semver.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/jsm_test.ts
[FEAT] consumer filter_subjects support - this feature is exclusive of the filter_subject but allows a consumer to filter multiple subjects in a stream. To set, specify filter_subjects instead of filter_subject or if using consumer options builder filterSubject() can be called multiple times.
[CHANGE] filter_subject (and filter_subjects) can be updated, the server removed this restriction
=> [FEAT] multiple consumer filters

nats-base-client/objectstore.ts, nats-base-client/types.ts, tests/jetstream_test.ts, tests/kv_test.ts, tests/objectstore_test.ts
Currently, it is possible to add the same object twice, but not trigger the prune functionality, thus data assets are found twice in the stream. The option `previousRevision` allows the client to specify the revision that the previous object represented (`0` for not expecting the object to exist in the stream). If the update of the metadata entry fails, the data chunks are removed.
=> [FIX] add support `previousRevision` in ObjectStorePutOps

nats-base-client/authenticator.ts, nats-base-client/options.ts, nats-base-client/protocol.ts, nats-base-client/types.ts, tests/auth_test.ts, tests/jetstream_test.ts, tests/properties_test.ts
- it is now possible to specify multiple authenticators, previously this was rejected by the client.
- all generated/specified authenticators are aggregated, and their authentication results are aggregated. Note that creds and jwt authenticators write the `nkey` and `sig` properties, so if both are specified, it is important that they both use the same nkey.
=> [FEAT] multiple authenticators

nats-base-client/jsmdirect_api.ts, nats-base-client/jsmsg.ts, nats-base-client/jsmstream_api.ts, nats-base-client/kv.ts, nats-base-client/msg.ts, nats-base-client/service.ts, nats-base-client/types.ts, tests/basics_test.ts, tests/jetstream_test.ts, tests/jsm_test.ts, tests/kv_test.ts
[FEAT] Added json()/string() utilities to Msg, JsMsg, KvEntry, StoredMsg, DirectMsg this allows clients to decode payloads easier while still requiring accountability on the client (as decoding can fail)
Fix #476
=> [FEAT] Added json()/string() utilities to Msg and other variants

nats-base-client/headers.ts, tests/headers_test.ts
A malformed status line, the client tried to parse a space which would yield NaN - this is degenerate, but at least it doesn't have an unexpected code value
=> [FIX] malformed status created a NaN code

nats-base-client/jsmdirect_api.ts, nats-base-client/jsmstream_api.ts, nats-base-client/types.ts, tests/headers_test.ts
[FIX] Added StoredMessage#timestamp returns the ISO message timestamp as provided by the server (`#time()` returns a `Date` object which will have lower precision)
[FIX] `StreamInfo.created` to be a `string` (was marked as `Nanos`), `StreamState#first_ts` to be a string.
Fixes https://github.com/nats-io/nats.js/issues/556
=> timestamp types were incorrectly tagged as Nanos rather than strings

tests/jetstream_test.ts, tests/jsm_test.ts
Since 2.9.15, the server handles inbound messages in a separate execution context, which is an optimisation, but it also means clients can't rely on flushing published messages to ensure that JetStream has it stored and accounted. That behaviour was never guaranteed, and it worked only because of the lack of this optimisation.
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
=> Fix JetStream tests by awaiting publish acks

nats-base-client/jslister.ts, nats-base-client/jsmstream_api.ts, tests/jsm_test.ts
[FIX] Lister was filtering stream responses for objectstore and kv, but offset calculations are made as a whole. Added check of total count that lister results are not duplicated.
=> fixed duplicate kv/object store lists when unexpected stream types were included

bin/fix-os.ts, nats-base-client/base64.ts, nats-base-client/objectstore.ts, src/deno_transport.ts, tests/objectstore_test.ts
[FIX] [BREAKING] [OS] previous versions of object store incorrectly base64 encoded without padding - this made javascript created entries be incompatible with other clients. The tool bin/fix-os.ts can be used to fix existing object stores - however it is important for a backup of the stream to be made prior to using it.
FIX #489
=> [FIX] ObjectStore meta subject entries name encoding

nats-base-client/types.ts, tests/jetstream_test.ts
[FEAT] [JS] `StreamConfig` can specify a `subject_transform` to apply a transform to incoming messages before anything else.
[FEAT] [JS] `StreamSource` configurations can specify a `SubjectTransformConfig` to map a source and destination pattern.
=> [FEAT] subject transforms

legacy_jetstream.md, nats-base-client/consumermessages.ts, nats-base-client/consumers.ts, nats-base-client/nats.ts, nats-base-client/types.ts, tests/consumers_test.ts
[FIX] accounting for pull request messages was happening when the iterator executed, creating additional pulls on the next message to be processed.
[FIX] tagged consumers api as beta, deprecated legacy subscribes/fetch/etc.
=> fixed buffering triggers

nats-base-client/consumer.ts, nats-base-client/jsclient.ts, nats-base-client/jsmstream_api.ts, nats-base-client/stream.ts, nats-base-client/types.ts, tests/consumers_test.ts, tests/helpers/launcher.ts, tests/jstest_util.ts, tests/streams_test.ts
[FEAT] added the ability to `get()` a stream name - this API returns an object that allows for easy access to `alternates()`, `best()` (best mirror as per nats-server), `getConsumer()` to get an existing consumer (or ordered consumer) associated with the stream, and `getMessage()` to retrieve a message manually. This functionality is already available via JSM or via the consumer's API; this provides more convenient access.
=> streams object

.github/workflows/test.yml, nats-base-client/consumer.ts, nats-base-client/consumers.ts, tests/consumersordered_test.ts
[FIX] relaxed simplified ordered consumer to not required 2.10 unless using filtered_subjects
=> relax ordered consumer requirements

jetstream/jsclient.ts, jetstream/jsm.ts, jetstream/jsmstream_api.ts, jetstream/types.ts, nats-base-client/core.ts, nats-base-client/internal_mod.ts, nats-base-client/mod.ts, nats-base-client/msg.ts, nats-base-client/nats.ts, nats-base-client/protocol.ts, nats-base-client/service.ts, tests/basics_test.ts
[FEAT] client can now publish/request/respond with strings or Uint8Array, not that JSON still requires an encoder
[FEAT] Msg#json() and related can now specify a [reviver](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#the_reviver_parameter) function for rehydrating the JSON input.
=> pub string

nats-base-client/core.ts, nats-base-client/internal_mod.ts, nats-base-client/mod.ts, nats-base-client/service.ts, tests/helpers/service-check.ts, tests/service_test.ts
[CHANGE] [SRV] [BREAKING] info operation now returns endpoints instead of `subjects`. Endpoints contain not only the subject for each of the endpoints but also the associated endpoint metadata
[CHANGE] [SRV] [BREAKING] removed NamedEndpointStats#metadata reference; use `EndpointInfo#metadata` instead
=> Changes to service info and stats

nats-base-client/protocol.ts
When a fast producer dominates the event loop and sends more data than can fit into the outbound buffer, an inline flush happens - but on the first command sent to the server, an auto-flush is scheduled on the next event loop. The timer for this auto-schedule flush was not managed. 
In a bench-type scenario where the client is trying to send a significant amount of data, the timers accumulate, degrading the client's performance. This fix removes the scheduled timer whenever an inline flush happens, greatly improving the client's performance.
=> [FIX] flusher timers

src/deno_transport.ts
@caspervonb this is effectively your simplification, including the changes to support `debug` and the closing promise.
=> [DENO] optimization on write to just queue up

examples/services/03_bigdata-client.ts, examples/services/03_bigdata.ts, examples/services/03_util.ts, nats-base-client/mod.ts
[DOCS] example for a service that generates a requested amount of data, and then sends it in chunks, including the client making the request and processing the response
=> chunk example

jetstream/consumer.ts, jetstream/tests/consumersordered_test.ts
=> [FIX] allow `headers_only` on the ordered consumer options for new JetStream API

jetstream/consumer.ts, jetstream/tests/consumers_test.ts, nats-base-client/nats.ts
[FIX] pull adds a status listener on every call, and has no mechanism for removing it - this modifies it so that if the status iterator closes it is removed from the list
Fixes #546
=> status iterator doesn't cleanup if the iterator is stopped

jetstream.md
A variable name changes from the variable assignment when calling `consume` and the variable used in the `for` loop.
=> Fixed bug in code example

jetstream/consumer.ts, jetstream/jsmstream_api.ts, jetstream/tests/consumersordered_test.ts
[FIX] ordered consumer sets redeliver to 1, and to be mem based
[TEST] ordered consumer by date turns into sequence 
[LINT] fixed some linter warnnings
=> [FIX] ordered consumer max_redeliver set to 1, and to use mem_storage

nats-base-client/protocol.ts
change to queueMicrotask() instead of scheduling a timer for flushing - also made flush() do its work inline rather than scheduling a timer. The original node nats library performed a setImmediate(), which is not available in other runtimes.
The performance change for deno is about 7% improvement; on node the performance is up by 1200%
FIX https://github.com/nats-io/nats.js/issues/581
FIX https://github.com/nats-io/nats.js/issues/438
=> optimization change to send outbound messages quicker

jetstream/jsmconsumer_api.ts, jetstream/jsutil.ts, jetstream/tests/consumers_test.ts, jetstream/tests/consumersordered_test.ts, jetstream/tests/jsm_test.ts
=> [CHANGE] require consumer/stream names to not contain spaces, newlines, carriage returns or tabs

jetstream/jsapi_types.ts, jetstream/jsmstream_api.ts, jetstream/tests/jetstream_test.ts, jetstream/tests/jsm_test.ts
[CHANGE] remove `subject_transform_dest` from `StreamSource` and `StreamSourceInfo` - this feature is replaced with `subject_transforms`. Note this feature was never released on nats-server, and was retracted in favor of `subject_transforms`.
https://github.com/nats-io/nats-server/pull/4557
=> remove `subject_transform_dest`

jetstream/jsapi_types.ts, jetstream/jsmstream_api.ts, jetstream/tests/jsm_test.ts, nats-base-client/semver.ts
added configuration to support the new compression options on the store.
Fixes #594
=> [FEAT] stream `compression` option

jetstream/jsapi_types.ts, jetstream/jsmstream_api.ts, jetstream/tests/jsm_test.ts, nats-base-client/semver.ts
[FEAT] [JETSTREAM] added support for `consumer_limits` on stream create/update configurations - this feature enables the stream to provide a default assigned to consumers when values are not specified.
=> [FEAT] consumer limits

jetstream/jsclient.ts, jetstream/objectstore.ts, jetstream/tests/objectstore_test.ts, jetstream/types.ts
[JETSTREAM] [OS] [CHANGE] The `update()` method will now delete the previous meta for an object - previously, it reused the storage of the entry - this matched the original go client implementation.
[JETSTREAM] [OS] [CHANGE] links now always store link metadata - previously, if, on the same object store, it would duplicate the source metadata entry.
[JETSTREAM] [OS] [FIX] links of links are now rejected
[DOC] added documentation on the object store API
=> os changes to update and links

jetstream/tests/consumers_test.ts, jetstream/tests/jetstream_test.ts, nats-base-client/core.ts, nats-base-client/internal_mod.ts, nats-base-client/mod.ts, nats-base-client/queued_iterator.ts, tests/basics_test.ts, tests/iterators_test.ts
[FEAT] added a utility function `syncIterator()` to wrap an `AsyncIterables` so that elements can be extracted in a `sync` faction. Note messages and elements will continue to buffer in the iterable, so if you don't drain it or stop its source memory will grow - this is syntactic sugar, as the iterator can be had via `src[Symbol.asyncIterator]()`. This can be useful to process subscription messages one at a time; this is especially true on tests.
```javascript
const sub = nc.subscribe("foo");
nc.publish("foo");
nc.publish("foo");
const sync = syncIterator(sub);
console.log((await sync.next()).subject);
console.log((await sync.next()).subject);
```
=> [FEAT] sync subscription utility

jetstream/consumer.ts
[FIX] changed consumer so that a server consumer_deleted notification doesn't stop the iterator. The consumer will notify the condition, and continue to re-attempt to retrieve messages.
=> prevent consumer deleted from stopping iterator

nats-base-client/core.ts, nats-base-client/protocol.ts, nats-base-client/servers.ts
[FIX] on websocket rewriting of the urls requires additional information, added a hint to the url parse which designates whether gossiped URLs should be ws or wss based on current transport rather than on other heuristics.
=> Allow downstream implementations of url parse to know whether we are connected securely or not

jetstream/kv.ts, jetstream/tests/kv_test.ts, jetstream/types.ts
delete and purge now take an optional sequence. If the current key is not at the specified revision, the delete/purge fails
=> [FEAT] [KV] delete and purge at seq

jetstream/jsclient.ts, jetstream/kv.ts, jetstream/tests/kv_test.ts, jetstream/types.ts
[FIX] changed KV ordered consumers created by watch, to set `name` if supported by the server. This enables the client to be able to use the newer consumer APIs which can then be clamped down with permissions on filter
[FIX] removed unused JSM reference in the Views implementation
=> allow internal kv watch consumer to use filtered consumer api

Makefile, jetstream/consumer.ts, jetstream/tests/consumers_consume_test.ts, nats-base-client/queued_iterator.ts
[CHANGE] iterator close()/closed() now return a promise that could resolve to an Error, this simplifies upstream cases where it is necessary to know if there was an error while processing the iterator.
=> enhancements to downstream iterator use to determine if the iterator failed

.github/workflows/test.yml, jetstream/consumer.ts, jetstream/tests/consumers_consume_test.ts, jetstream/tests/consumers_fetch_test.ts, jetstream/tests/consumers_next_test.ts, jetstream/tests/consumers_ordered_test.ts, tests/helpers/launcher.ts
This change modifies the behavior of `fetch()` and `next()` to react to `consumer deleted` / `consumer not found` / `stream not found` server responses. Since these operations have a termination condition (the end of the `next()` or `fetch()`), such events are appropriate. 
Ordered consumers work similarly with `next()` and `fetch()` as described above. Applications that use next()/fetch() should trap errors, and re-attempt as desired.
`consume()` API however will keep reporting via its `status()` if there's an error related to the stream or consumer. Clients that want to stop processing during a consume on consumer deleted/stream not found type errors should setup a listener and then call `stop()` on the consumer if those conditions are reported and the desired behavior is to stop …
=> [CHANGE] [JS] [CONSUMERS] fetch()/next() can fail on consumer/stream errors

nats-base-client/nats.ts
[FIX] jetstream() api implementation incorrectly typed options as JetStreamManagerImpl - should have been JetStreamManagerOptions - this is only in the implementation, the types are correct on the interface.
=> Fix incorrect type in implementation of `jetstream()` api - it is correct in the interface.

.github/workflows/test.yml, Makefile, jetstream/tests/jetstream_test.ts, nats-base-client/core.ts, src/deno_transport.ts, unsafe_tests/tlsunsafe_test.ts
[FEAT] [CORE] connect to `handshake_first` configured NATS servers specify `{tls: {handshakeFirst: true}}` connection option. Note that the server must match the configuration option, and will only accept with a matching option.
=> [FEAT] `handshake_first` support

jetstream/kv.ts, jetstream/tests/kv_test.ts, jetstream/types.ts
Note this functionality requires server 2.10.0 or better
=> [FEAT] [JETSTREAM] [KV] support multiple key filters on watchers/history

Makefile, nats-base-client/core.ts, nats-base-client/nats.ts, tests/basics_test.ts
This effectively uses a message as a set of parameters. The client will use the provided message as the source for subject, data, reply and headers. Note that this will work with any argument that satisfies the message interface, but it is not of interest to most applications.
=> [FEAT] [CORE] added the ability to publish by providing a Msg argument

jetstream/jsclient.ts, jetstream/tests/kv_test.ts, nats-base-client/idleheartbeat_monitor.ts, src/deno_transport.ts
[FIX] [JS] [KV] watcher reset due to a server restart could fail because the server would report the consumer as existing
[FIX] [JS] [KV] watcher reset if successful, could still get heartbeat missing reports which would cause the ordered consumer to reset when it didn't need to.
Fix #688
=> [FIX] Kv Watcher reliability during server restarts

jetstream/jsbaseclient_api.ts, jetstream/jsclient.ts
[FIX] [JS] [LEGACY] reset order consumer would throw an error if it failed to recreate the consumer - now if the failure is due to a 503 or a timeout, it will continue to retry,
=> [FIX] more robust watcher in case consumer is recreated while the cluster is flapping

jetstream/jsclient.ts, nats-base-client/protocol.ts, tests/helpers/launcher.ts, tests/resub_test.ts
[FIX] fixed an issue with ordered consumer where resetting the consumer didn't send the UNSUB, creating a situation where if there was no disconnect from the client, two subscriptions would be active on the server.
FIX #691
=> [FIX] legacy order consumer subscription leak

jetstream/kv.ts, jetstream/tests/kv_test.ts
=> [FIX] [JS] [KV] fixed an issue where `maxBucketSize` (deprecated option) overrode `max_bytes`

jetstream/consumer.ts, jetstream/jsclient.ts, jetstream/jsmsg.ts, jetstream/tests/jsmsg_test.ts
[FIX] [JS] JsMsg#ackAck() didn't provide a way to customize the timeout. Added optional option with timeout for ackAck(), and also defaulted the timeout to match the JSClient's timeout (as provided by the JetStreamOptions)
=> Honor JS timeout in ackAck() and also allow to override

nats-base-client/nats.ts, tests/basics_test.ts, tests/mrequest_test.ts
[FIX] `requests()` with `noMux` leaked subscriptions if the request ended in an error
[FIX] `requestMany()` with `noMux` leaked subscriptions on permissions error
=> fixed noMux (request/requestMany) leaked subscriptions

jetstream/objectstore.ts
The library interface, defined by the `ObjectStoreOptions` type, currently expects a parameter named `replicas` to specify the number of replicas for the object store. However, internally, the correct parameter to be used is `num_replicas`. To align with the existing initialization method of KV, the initialization method of OB should also map `opts.replicas` to `sc.num_replicas`. This ensures consistency and proper utilization of the `replicas` parameter within the object store configuration.
=> Map `opts.replicas` to `sc.num_replicas` in Object Store init

jetstream/jsmstream_api.ts, jetstream/kv.ts, jetstream/tests/kv_test.ts
- added a required transform to the source
- added the kv subject when sources are present
=> fix(kv): fixed an issue where kv sources were not properly processed

jetstream/consumer.ts, jetstream/tests/consumers_ordered_test.ts
=> fix(jetstream): ordered pull consumer would never fail to reset on initial creation if there was an error

jetstream/jsapi_types.ts, nats-base-client/core.ts, nats-base-client/service.ts
doc(core,jetstream): jsdoc for fields that are in nanoseconds, but where not specified in the description - jsdoc erases the type alias and marks as number
fix(services): `processing_time` was reported in millis instead of nanos
=> nano fixes

jetstream/tests/jsm_test.ts, tests/auth_test.ts, tests/authenticator_test.ts
clamp tests to reference jwt.js at a specific version
=> [TEST] clamp JWT lib used by tests
