README.md, doc/snippets/autounsub.ts, doc/snippets/basics.ts, doc/snippets/connect.ts, doc/snippets/queuegroups.ts, doc/snippets/service.ts, doc/snippets/service_client.ts, doc/snippets/stream.ts, doc/snippets/wildcard_subscriptions.ts, nats-base-client/nats.ts, nats-base-client/protocol.ts, nats-base-client/types.ts, src/connect.ts, tests/basics_test.ts
Start of rewrite for the Readme - also added a bunch of snippets (which are directly inserted into the Readme).
=> Updated readme and added example snippets

examples/nats-events.ts, examples/nats-rep.ts
fixed spurious encoding where none was needed when the data is echoed.
added decoding when printing status notifications
=> fixes to tools from api changes

examples/bench.js, nats-base-client/bench.ts
- ported bench example to JS
- added csv serialization
=> reusable bench

nats-base-client/authenticator.ts, nats-base-client/buffer.ts, nats-base-client/codec.ts, nats-base-client/databuffer.ts, nats-base-client/encoders.ts, nats-base-client/headers.ts, nats-base-client/internal_mod.ts, nats-base-client/msg.ts, nats-base-client/parser.ts, nats-base-client/protocol.ts, nats-base-client/util.ts, src/deno_transport.ts, tests/databuffer_test.ts, tests/doublesubs_test.ts
collapse of concats
removed TextEncoder/TextDecoder throwaways.
=> pub performance

nats-base-client/internal_mod.ts, nats-base-client/ipparser.ts, nats-base-client/protocol.ts, nats-base-client/servers.ts, nats-base-client/types.ts, src/deno_transport.ts, tests/parseip_test.ts, tests/servers_test.ts
=> added ability to remember the tlsHost name

README.md
FIX https://github.com/nats-io/nats.ws/issues/50
=> added documentation on using authenticators

README.md, doc/snippets/json.ts, examples/nats-pub.ts, nats-base-client/codec.ts
- [fix] missing type from the JSON codec which the compiler was angry about
- [fix] sample had rogue `boolean` option
- [doc] added documentation on the JSONCodec<T> feature
=> fix untyped codec implementation

nats-base-client/subscription.ts, tests/sub_extensions_test.ts
[change] added an internal promise that resolves when a subscription is closed - this will benefit downstream wrappers such as jetstream to detect when their underlying subscription is closed.
=> support downstream sub closed

nats-base-client/headers.ts, nats-base-client/protocol.ts
- [fix] changed header code interface to be always a number simplifying downstream logic
- [fix] linter warning
=> simplify header code checks downstream

nats-base-client/typedsub.ts, tests/auth_test.ts, tests/basics_test.ts, tests/protocol_test.ts
- [fix] typedsub had inadvertent dependencies on its own modules which fail in other runtimes
- [tests] added more coverage tests (coverage is not properly calculated)
=> fixes for upstream and tests

nats-base-client/internal_mod.ts, nats-base-client/jsclient.ts, nats-base-client/jsm.ts, nats-base-client/nats.ts, nats-base-client/protocol.ts, nats-base-client/queued_iterator.ts, nats-base-client/subscription.ts, nats-base-client/typedsub.ts, tests/iterators_test.ts, tests/jetstream_test.ts
this fixes implementation details to clients
=> [fix] leak of implementation type to JS api (QueuedIterator is now an interface

nats-base-client/error.ts, nats-base-client/jsbaseclient_api.ts, nats-base-client/jsclient.ts, nats-base-client/jsutil.ts, nats-base-client/msg.ts, tests/jetstream_test.ts, tests/jsm_test.ts
- [fix] normalized error code handling:
- codes are string representation of the number
- description is lowercased string
- constants simply reference the string code
=> normalize error handling

nats-base-client/protocol.ts
=> [fix] the mux inbox was doubly initialized with a prefix 

nats-base-client/types.ts
=> [fix] added 'cluster' as possible property in ServerInfo

nats-base-client/jsmsg.ts, tests/jetstream_test.ts
=> [fix] fixed an issue where preventing double-acks prevented repeat invocations of `working`

nats-base-client/headers.ts, tests/headers_test.ts, tests/parser_test.ts
FIX https://github.com/nats-io/nats.js/issues/430
=> Fixed header-separator

nats-base-client/jsstream_api.ts
FIX https://github.com/nats-io/nats.js/issues/428
=> removing rogue reference to window

examples/jetstream/jsm_readme_jsm_example.ts, jetstream.md, nats-base-client/jsstream_api.ts, nats-base-client/types.ts, tests/jsm_test.ts
[FEAT] added the ability to purge streams by subject, sequence, or trimming to a specific number of messages.
=> advanced purge operations

nats-base-client/internal_mod.ts, nats-base-client/jsstream_api.ts, nats-base-client/mod.ts
[FIX] added missing export `ConsumerInfo`
[FIX] removed unused import
=> exported `ConsumerInfo`

Makefile, nats-base-client/jsconsumeropts.ts, nats-base-client/kv.ts, nats-base-client/types.ts, tests/helpers/mod.ts, tests/helpers/semver_test.ts, tests/jetstream_test.ts, tests/kv_test.ts
FIX https://github.com/nats-io/nats-architecture-and-design/issues/33
=> [FEAT] support `DeliverPolicy.LastPerSubject`

nats-base-client/kv.ts, tests/kv_test.ts
- [feat] added support for key/value codecs, on JavaScript stack the values are always byte arrays, so different codecs are required for keys and values.
- [feat] added validation to keys and buckets
=> kv updates - codecs/validation

nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/jsmconsumer_api.ts, nats-base-client/types.ts, tests/jetstream_test.ts
model changes SequencePair.last_active, ConsumerInfo#push_bound, ConsumerConfig#deliver_group
https://github.com/nats-io/nats-architecture-and-design/issues/43
=> ConsumerConfig model changes

nats-base-client/kv.ts, tests/ekv_test.ts, tests/jetstream_test.ts, tests/kv_test.ts
[FEAT] added some kv extensions to delete subkeys as this is super useful to some applications
[FIX] changed kv#keys() to omit keys that have been deleted
[TESTS] Added tests for multiple jetstream pull consumers on the same durable.
=> kv extensions

jetstream.md, tests/jetstream_test.ts
- [doc] added section in the doc about queue consumers
- [test] added a test for qgroup consumer using autoack
=> doc qgroup consumer

nats-base-client/jsclient.ts, nats-base-client/jsconsumeropts.ts, nats-base-client/types.ts, tests/jetstream_test.ts
=> [FEAT] implement JS consumer `bind`

nats-base-client/codec.ts, tests/codec_test.ts
Makes it possible to customize the JSON decoder at the message level.
=> added support for custom reviver in JSONCodec

jetstream.md, tests/jstest_util.ts
[FIX] formatting for the doc
[CHORE] exposed stream configuration of test stream generator
=> doc formatting issues from user pr

jetstream.md, nats-base-client/jsmsg.ts, nats-base-client/types.ts, tests/jetstream_test.ts
=> [FEAT] add support for nak delay

nats-base-client/internal_mod.ts, nats-base-client/nats.ts, nats-base-client/semver.ts, nats-base-client/types.ts, tests/helpers/mod.ts, tests/semver_test.ts
added internal support to get the semver of the connection server - this will be required for some JetStream operations.
=> server version

nats-base-client/kv.ts, tests/kv_test.ts
=> [FEAT] added (internal for now) ability to purge deletes

src/deno_transport.ts, tests/jetstream_test.ts
=> [RELEASE] bumped client version to 1.7.0

tests/auth_test.ts
=> [TEST] added a test to verify that an iterator on a subscription permission error will throw the permissions error

jetstream.md
This PR fixes a wrongful name of variable used.
=> docs: fix wrong name for variable

nats-base-client/jsmconsumer_api.ts, nats-base-client/jsutil.ts, tests/jsm_test.ts
This fix doesn't define what a valid consumer name should be, but at least is consistent with other validations done by the javascript client.
=> [FIX] Added validation of `name` option in ConsumerConfig

nats-base-client/objectstore.ts, tests/objectstore_test.ts
- updating meta of a deleted object is not allowed
- updating the meta to point an already existing name is not allowed
=> [FIX] [OS] added additional checks to update

nats-base-client/kv.ts, nats-base-client/types.ts, tests/kv_test.ts
=> [FEAT] [JS] [KV] exposed size of the bucket via `KvStatus.size`

nats-base-client/objectstore.ts
Reference: https://github.com/nats-io/nats.go/blob/f4102422df7df83b2032318fd14a248c45f113e1/object.go#L232
Breaking change
=> [FIX] object store digest type

nats-base-client/service.ts, tests/service_test.ts
[CHANGE] service handler to return a promise
=> Service promise

nats-base-client/protocol.ts, tests/auth_test.ts
=> [FIX] remove remembering of a permissions error

nats-base-client/protocol.ts, nats-base-client/subscriptions.ts, tests/auth_test.ts
These were already reviewed in dev, but will benefit the setup having connection problems behind kubernetes LB.
=> Merging two fixes from dev that remove ambiguity on connection errors

nats-base-client/jsclient.ts, tests/jetstream_test.ts
=> [FIX] [JS] publish with `expect.lastSequence` or `expect.lastSubjectSequence` set to `0` was not honored

nats-base-client/service.ts
Fixes the downstream builds for nats.ws and nats.js
=> [FIX] downstream builds

tests/helpers/cluster.ts
`cluster --cluster 3 --chaos 10000 --jetstream` will start a 3-node jetstream cluster that starts behaving erratically every 3000 seconds (the server processes are killed and replaced by another service at some random time in the future).
=> [TEST] chaos

tests/auth_test.ts, tests/authenticator_test.ts, tests/jetstream_test.ts, tests/service_test.ts
fixed some tests that have been flapping recently, as well as corrected logging output.
=> [FIX] [TEST] fixed a flapper test

tests/jetstream_test.ts
[TEST] the change to the test exposed a error where the resource limits of the test server were exceeded.
=> [TEST] fixed resource limits on test

bin/fix-os.ts, nats-base-client/objectstore.ts, nats-base-client/types.ts, tests/objectstore_test.ts
=> [FEAT] [OS] added get/putBlob() convenience methods

nats-base-client/jsutil.ts, tests/jetstream_test.ts, tests/service_test.ts
added ability for client to see on pull consumers to handle consumer deleted.
=> pull consumer - consumer deleted notifications

nats-base-client/consumers.ts, nats-base-client/types.ts, tests/consumers_test.ts, tests/consumersordered_test.ts
API simplification for ordered consumer
=> ordered get

nats-base-client/consumer.ts, nats-base-client/consumermessages.ts, tests/consumers_test.ts, tests/consumersordered_test.ts
simplified consumer was leaking subscriptions
=> consumer sub leaks

examples/bench.js, nats-base-client/bench.ts, nats-base-client/util.ts, tests/bench_test.ts
[bench] added flag to control pendingLimit
[bench] added --rep, allowing --req/--rep to be run in different processes
[bench] changed Perf to use performance.now
=> some bench enhancements

.github/workflows/test.yml, src/deno_transport.ts
=> [CI] nats-server bump

jetstream/tests/consumers_test.ts, jetstream/tests/consumersordered_test.ts, tests/basics_test.ts, tests/reconnect_test.ts
[LINT] fixed some linter warnnings
=> [TEST] ordered consumer by date turns into sequence

nats-base-client/core.ts, nats-base-client/protocol.ts, tests/reconnect_test.ts
Possibly fixes https://github.com/nats-io/nats.ws/issues/205 as well.
=> Fix auth timeout

nats-base-client/protocol.ts, nats-base-client/transport.ts, src/deno_transport.ts
This is actually a cleanup handler to aid in fixing an issue with firefox
https://github.com/nats-io/nats.ws/pull/207
=> Fix firefox

jetstream/consumer.ts, jetstream/jsclient.ts, jetstream/kv.ts, jetstream/objectstore.ts, jetstream/tests/consumers_test.ts, jetstream/tests/jetstream_test.ts, jetstream/types.ts, tests/basics_test.ts, tests/reconnect_test.ts
=> [FIX] expanded/referenced constants for JsHeaders

jetstream/jsapi_types.ts, jetstream/jsmstream_api.ts, jetstream/tests/jsm_test.ts, nats-base-client/semver.ts
implement https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-36.md
Fix #588
=> [FEAT] implements support for `subject_transforms` on StreamSources/Mirrors

bin/os_compatibility.ts, bin/os_compatibility_test.ts, jetstream/objectstore.ts
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
=> Object Store compat tests

bin/docker/Dockerfile, bin/os_compatibility.ts
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
=> Add Dockerfile

jetstream/kv.ts, jetstream/objectstore.ts, jetstream/tests/kv_test.ts, jetstream/tests/objectstore_test.ts, jetstream/types.ts
=>  [FEAT] kv and os compression

README.md
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
=> Add nats by example link

.github/workflows/test.yml, jetstream/jsmsg.ts, jetstream/tests/jsmsg_test.ts
[FIX] JsMsg.ackAck() was not waiting for a proper response from the server. Now it will return false, if the reply subject is not set, or the message was already ack'ed. And will reject if the there's a problem with the response.
=> ackAck() always returning false

README.md
=> [DOC] added `handshakeFirst` tls option

jetstream/objectstore.ts, jetstream/tests/objectstore_test.ts
=> [TEST] added test to cover fix for #717

nats-base-client/servers.ts, tests/servers_test.ts
=> [FIX] identify ipv6 encoding an ipv4 as ipv6
